### ISSUE TITLE
Add "Wowza Streaming Cloud REST API"

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#247]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://sandbox.cloud.wowza.com/en/docs/api/v1
**Name**: Wowza Streaming Cloud REST API
**Valid**: No
**RelativeHost**: No
**Category**: media
**Twitter**: https://twitter.com/wowzamedia
**Logo**: https://pbs.twimg.com/profile_images/876811954517532673/vQ3blMcV_400x400.jpg

**Comment by MikeRalphson** [comment]
```yaml
 - code: ARRAY_LENGTH_SHORT
              message: 'Array is too short (0), minimum 1'
              params:
                - 0
                - 1
              path:
                - properties
                - live_stream
                - properties
                - stream_targets
                - items
                - required
```
