### ISSUE TITLE
Add "Weatherbit.io" API

### ISSUE THREAD

**Issue by hkosova** [APIs-guru/openapi-directory#263]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://www.weatherbit.io/static/swagger.json
**Name**: Weatherbit.io
**Valid**: No - might be automatically patched by scripts

**Comment by MikeRalphson** [comment]
```json
{
  "name": "SyntaxError",
  "message": "Validation failed. /paths/bulk/{file}.json.gz/get is missing path parameter(s) for {file}",
  "stack": "SyntaxError: Validation failed. /paths/bulk/{file}.json.gz/get is missing path parameter(s) for {file}"
}
```

**Comment by hkosova** [comment]
Oops, Swagger Editor missed that.

From the operation desciption it looks like it should be:
```
- in: path
  name: file
  required: true
  type: string
  enum:
    - current
    - forecast16d
```
but it's a third-party API so I'm not sure. :woman_shrugging:
