### ISSUE TITLE
Add "Car Registration API" API

### ISSUE THREAD

**Issue by infiniteloopltd** [APIs-guru/openapi-directory#289]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://swaggerhub.com/apis/infiniteloopltd/CarRegistration/1.0.0
**Name**: Car Registration API

**Comment by MikeRalphson** [comment]
Hi @infiniteloopltd thanks for the submission.

Do you have a version of the API definition where the `host` property points to `www.regcheck.org.uk` and not the swaggerhub mock server:

```yaml
# Added by API Auto Mocking Plugin
# host: www.regcheck.org.uk
basePath: /infiniteloopltd/CarRegistration/1.0.0
schemes:
 - https
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
```

And possibly with a `securityDefinition` which defines how the username and password are to be passed in?
