### ISSUE TITLE
Add "SocialBicycles" API

### ISSUE THREAD

**Issue by dschep** [APIs-guru/openapi-directory#356]
**Format**: Swagger 1.x
**Official**: YES
**Url**: https://app.socialbicycles.com/api/docs.json
**Name**: SocialBicycles
**Category**: transport
**Twitter**: SocialBicycles

**Comment by MikeRalphson** [comment]
Thanks for the contribution! Unfortunately the definition fails validation. One issue is parameters like this:

```yaml
- description: Return results from all networks
          in: query
          name: all_networks
          required: false
          type: 'Virtus::Attribute::Boolean'
```

Where `'Virtus::Attribute::Boolean'` isn't a valid Swagger 1.0 type.
