### ISSUE TITLE
Add "Global wine score" API

### ISSUE THREAD

**Issue by guiviaje** [APIs-guru/openapi-directory#467]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: ~~https://globalwinescore.docs.apiary.io/~~
**Url**: https://globalwinescore.docs.apiary.io/api-description-document
**Name**: Global wine score
**Valid**: Yes
**Twitter**: GlobalWineScore
**Category**: open_data

**Comment by MikeRalphson** [comment]
Hi, in the interim there seems to have been an error crept in;

```yaml
securityDefinitions:
  Token authentication:
    type: apiKey
    name: Authorization
    in: header
    description: See Authentication section above
security:
  - Token: []
```

The `security` stanza should point at `Token authentication` not `Token`. And for forwards compatibility I'd recommend not using a space in the identifier.
