### ISSUE TITLE
Add "KeyServ" API

### ISSUE THREAD

**Issue by JawzoD3TH** [APIs-guru/openapi-directory#537]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://keyserv.solutions/v1/spec.json
**Name**: KeyServ API

**Comment by MikeRalphson** [comment]
Hi, thanks for the contribution. Unfortunately your API definition doesn't pass validation.

OpenAPI 3.x documents should not contain `produces` or `consumes` arrays.

```yaml
{
  "x-generator": "NSwag v12.0.13.0 (NJsonSchema v9.13.17.0 (Newtonsoft.Json v9.0.0.0))",
  "openapi": "3.0.0",
  "info": {
    "title": "KeyServ API Spec",
    "version": "1.0.0"
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
 ...
}
```

Also `type: file` is no longer valid in `schemaObjects`.

Perhaps these are bugs in that version of NSwag?

**Comment by JawzoD3TH** [comment]
Used the latest version of NSwag Studio.

Kindly check if this Swagger2 spec is any better:
https://keyserv.solutions/v1/s2.json

Best Regards,
J Hassim

**Comment by MikeRalphson** [comment]
Hmm, this also fails to validate:

```yaml
  "host": "ws:",
  "basePath": "//",
  "schemes": [
    "https"
  ],
```

Changing it to 

```yaml
  "basePath": "/",
  "schemes": [
    "ws"
  ],
```
makes your definition validate ok, but it seems NSwag Studio doesn't understand `ws://` urls.
