### ISSUE TITLE
Feature request: include logo thumbnail in base64

### ISSUE THREAD

**Issue by roipoussiere** [APIs-guru/openapi-directory#552]
It's a very good idea to add a field in OpenAPI format to include logo.

In order to get all APIs data as we clone the project and do not depend of remote content that can disappear some day, it might be interesting to also have a thumbnail version of the logo included *in* the yaml file. It could be a base64 version of the logo with a maximum width and height to 100px, in a new `thumbnail` element under `x-logo`.

For instance, with GitLab it could be:

```yaml
  x-logo:
    backgroundColor: '#FFFFFF'
    thumbnail: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGQAAAAjCAIAAADt3TjXAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH4wMUFis1/LefHAAACfNJREFUaN7lmFtsXMUZx//fzDln17trr++J7cR2HOzE8TUmATcBRFoItwpEikBtKaIXHkpRHyqkFqntS/vSp0pUFFpQBUFNECSFpkmcYJLYxAQCKSSQxDa28SV2Eif2er33PefMTB/Wl/UtcWypEssnP/jMzH7zzW++2zlQcyR2+uTV3z6tli3xji+u/OYplULCMEcCu14ON+2JHH8Xy5Nw055w097Qf3YjVWQ2LBkORU8cYZ6M6LGmZaoO7H6Z5+RHWg6lLKzwvt3KMqHpZudZGQosndSuvxHjILKHBuTYaCrCkjJ8ZD9L9wIQo8PiyqUlapUy2vYeuT0ApG/EGupPQVhidFhcvQylAMhIOH7+9NKUitEr9vAEaGnGYqfaUhCW1dMpA/7E/6Tp4y/+aWlKrf4eOe6b0MN4cO9rKQgrsCfpVIzZV4djHx5dgtJIa5OyrWk9QxdiJ1tTCpaMhGInW8H59JwnPXhgz1JgNf2LuDb1yLNyAm+8klKwwk17lW3PnGR2f7cMBW+MVPM+2+8D0fQQkX1xYCrAv/6wpIgcO8hc7tmpeuSKfXnwhjQG336dZ2bPLo9+nz3YtxxDLcsOhSPhcERKmTyu1P8P1kSwCP+YGBqY4Q4TsRk2208bN1Uutg6OjdrDF+eOK9OMtr1nbKhfSm0V8sDhlouXhmNxkwBnmrOmsnxLY0Ni9s8v/GNL482Nm+oA7N13OBgIPfn496Z+OzLie3t/c33ths0NNYvf8eVX36yqLN9y68b5Pcvs7bXG/ErS7D9o46/fQLqxLvSLsbG5eqRigaZ3lkCqt3/w+Zd2nu/oTs/wlJWuLitd7XY5jx4/eeZsx0RCZJxN3nEwGPb5ZzTSlhCjPn8kGr2hTX1j/lA4sqBn8fa3slcraDRnAVfRnuALv7dj8vqtqOLOQEdWMc31UIArf48cOsOK6hZvtH88cOBwC+fsx4/vyM/LmXBSIBAIOh1G4vGXP3+CJrcjAs3cmgDGGIFuLDcRI1ooDIWpxXZqq7IRNueek7yO8MndgR6b6FrpQSkQ1zLrGWUSZi0kQAENWeh+AUV/X7zR7Z09I6Njjzx0z4r83GRlmd6MqcfXdr+zsbayrno9AAIJIfa8c8iy7BX5OdvuaMQU4NnWqsGLlz8/29nbPxSPx7OzvFWV5TdvrOaMJaBblv3+iVNnvuiQUpQWF21uqC0syNcAqPOvKN2BSg2nFJScS8HwaJrHkOJasEghLc/gPCLEPC6HbAeyLYx2wByH4V0krOMnTuXn5lRvqLjGmu6e/tLVhckXk5mZYVmW2+26xq/GA6G33j7k8bgqK9ZwXTt3rqu17ePsLO9NZSUAiPPz7V2Ms+JVRXHL7OoeuDB46fHHHtIgbXmxDcwAj6HKgfPW3ALDNMUMklF1bd91Z9rzkFKA14H1AkIhehWhIWR7F507xm/ZPBG2pmleGLo8oVKqwsIVrjRnkrcltlIa53fduWWuCbPEm+F58oc7srMmLGncVP/8izv/+9nZBCwlZWHBikd33K9pHMCnZ84dam7r6PpKQ9yHYB+IQQIeCysNDMbBZ3oNKaeXBUOS+MKsODRNYG52MBjW2hASAERcDR2l7A2LITUeDGkaczkniIyPh/YdPCqEAEgq9ejD95YWF82XDea90dmDRDRFSgjhdBgOhxEIhacuIy83O0EKQENd1XstH37Z06chNIjYyMQhlUKpBduBK/EZp1ZwZyFwceE8qZTmYIyrWVaR5KqcwbAmxkmT7a/ymmcWA8vjSrNtaZpm4jE9w3Pf3bcTaMwfaD72wfKbpp7egTNfdPT2DyqlCCSVdKelLbQ4zeGIhKOautgCYYI7JrsaiRILQY7YjIgyjJjhcdvh+LzApK1c+TrBVDOmSVVq8MSgaOpCERyQl9pYwW3XPQzn3JXm/LK7/7ZvbQLgdBjrK9YCGB4eMS17mc3omH/84LutROyJHzycl5MF4PmXdiZd9exDmrblSXcxNXAETJtppsQ6Bq4lu4m0kJG/YIZnhuH2xJVK2kMoZOvwmrM3Jo7hU4s80tbGhoELQ1/1XZipgEHJBSxZbItweXg0EAjdsXVTgtT8iW1SQqFIPG7m5+Yy2vjs7E+ACnBYWE9glDRGumHzeRoxKAV3LiPMfK90OlAt55igkJbDap9e5JFqayqzsrwHm1t9Y+NTyYgTqQWO5s1IN017nhZUTaSzhAAQwiaiuGklVWw171uUgmo98QkjVr2hXKNV2/jdO+WpP6rRs9PBCMBjodCBvhh0mq6JOsk59Y4YOT22FEkcOUONQsyavmqlYIeo5hds47NgxiJh5eVkbbu9san5/Vdee+umsmK326WUGvWN6bohLHvKl6Y2rqtZd669e9eb+9eUFGVlZm6sqwSgabyzp+/KyOgEJinraysLVuYbhv7Rx6dHR3wg6urpy0h3i8nIsYXo7b9w7P2PQOTz+c+1d6+vKCtcma8BwMpG9sA+eeRn6vLxaS9TQGkcphtXIglziKTT6wiG48RpZmMB3UhCKAkVBvSkVAUF3cXv3YW8TTeaXGqr15WvLdnXdLS3f5ARgSCV2lRftaqoYLIKs6kIWFOyevt3trYcPxkIBFevKtxYV0lEuqbHotFLk+4mhAivLcmpWHvv3XccPNza3tnDOLt/+50Oh9F8tG1y04rOrr7PPm8ngBjd9e2tW26pB0DJtVb1H5AfPod4CFyfTD0MZ4G4nMz++qXzYGxG46q7KG+NmHbcUgMFJsTku6cI05qHWMOv4Vm1nJQspYzF4pxzh+P6jhmJRHVd03X9uivDkagrzUnzvd3EYnEpZVrSLM1qTJQVVIceU/4uEEt4OcVc6tMwOAFgOhvuNqyQNR1etvKWONIzoyqRSLwaKpPASYtqn2H1v0qNz8o0TxenhPpyl/zgWegZIAam4HegwwIUkYyEXGN907Ak9NV1lrIEFOA2UC2QcCoRo/Q17M6/YnEt6NfvG/xUcaZ1P+KPfAzXCigJSfBayNOgoBQzDIsma6KSSM9nJCwA0BjWSUAACiAqvo/taEklUgvASkhGCf/uflb1E9gxKIUyG3lOSDBdTSU0YuT0WFIymIQKHYYNaYE7+V2vsm0vIeVEu9akI5ManmPOfPn5X2CFUWoiyJkpDLdhRU0iYhppmg0FVDiRGYEAcuv49n9CcyEVhV0/q234KX9gH+XfDNuHdZqSLGOFlIID0JzEuYJHwwoL8Si79Q/8njdSldSiYAFAejG75w2qeQZuiyo0TmZatqakMtxEGkcDgTv5g01U/tiMtvYbCiuxdPPv2PY9qngl8pgrzZKCeYtIrbnMyr7PdxxDdjVSXbQbazRyqviDh2TmU0bgM4+lWIkTO/6NgtvxzRBSS/nWoWR3i+z6RNv2BJwr8Y2R/wEto6LYh/yciAAAAABJRU5ErkJggg=='
    url: 'https://api.apis.guru/v2/cache/logo/https_cloud.githubusercontent.com_assets_21603_24521837_642e411c-1585-11e7-817f-61082580b6f6.png'
```

While this adds long lines, this should not take too much space. For instance, the GitLab OpenAPI file currently weights 391.1kb, and with the modification above it becomes 394.6kb (less than 1% more space).

(if interested I can work on a script to add thumbnails for all current APIs)

**Comment by MikeRalphson** [comment]
Paging @pimterry to see if https://github.com/httptoolkit/openapi-directory-js already handles this?

**Comment by pimterry** [comment]
No, it doesn't. For my case I'm not that interested in thumbnails, and most images aren't that big anyway.

I'd definitely find having the image data more readily available useful though. Maybe we could have a script that automatically pulls the logo (without transformation) and stores it alongside the spec? Then everybody can thumbnail it themselves easily in whatever size/format they'd like.

**Comment by roipoussiere** [comment]
> No, it doesn't. For my case I'm not that interested in thumbnails, and most images aren't that big anyway.

It was to prevent very big images to be included in the file. Some text editors may crash with very big lines, and also it can make the file less readable if lines are wrapped by the text editor. The base64 example text is 3592 characters long, so it's 45 lines with a 80 characters width, so it's not so annoying.

**Comment by MikeRalphson** [comment]
> it's 45 lines with a 80 characters width, so it's not so annoying

Unfortunately, I think adding 45 lines of base64 to an OAS definition **is** going to be annoying. If the APIs.guru API image cache is not sufficient for your needs, we can look at creating a `thumbnails.yaml` file in addition to the currently deployed assets, but I'm afraid this also won't be a priority unless we get more call for it.

**Comment by roipoussiere** [comment]
> Unfortunately, I think adding 45 lines of base64 to an OAS definition is going to be annoying.

Ok.

> If the APIs.guru API image cache is not sufficient for your needs, we can look at creating a thumbnails.yaml file in addition to the currently deployed assets

If we store thumbnails separately, we could store them directly with a more compressed and intelligible format, such as .png.

What about this?

```
APIs
└── gitlab.com
    ├── v3
    │   └── swagger.yaml
    └── logo.png
```

> but I'm afraid this also won't be a priority

If we are agree on a solution I can work on it. ;)

**Comment by MikeRalphson** [comment]
The thumbnails should be present in the deployed location for access via the API (which we recommend rather than cloning the repo directly).

Thus I'd prefer to store the thumbnails as:

`openapi-directory-api/v2/cache/thumbnail/http_1forge.com_logo.png` 

So they are available at stable URLs such as https://api.apis.guru/v2/specs/1forge.com/0.0.1/swagger.yaml

Containing (as now):

```yaml
x-logo:
    backgroundColor: '#24292e'
    url: 'https://api.apis.guru/v2/cache/logo/http_1forge.com_logo.png'
```

And an additional `thumbnail` property of the `x-logo` extension.

See https://github.com/APIs-guru/openapi-directory/blob/master/scripts/deploy.js for details.
