### ISSUE TITLE
Add "PhantAuth" API

### ISSUE THREAD

**Issue by szkiba** [APIs-guru/openapi-directory#582]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://www.phantauth.net/api.json
**Name**: PhantAuth

**Comment by MikeRalphson** [comment]
Thanks for the contribution, unfortunately your API definition contains some validation errors.

Specifically, where a `schema` object is of `type: array`, an `items` property/object must also exist:

```yaml
messages:
- "attribute paths.'/client'(post).[body].items is missing"
- "attribute paths.'/client'(post).[body].items is missing"
- "attribute paths.'/client'(post).[body].items is missing"
- "attribute paths.'/client'(post).[body].items is missing"
- "attribute paths.'/client'(post).[body].items is missing"
schemaValidationMessages:
- level: "error"
  domain: "validation"
  keyword: "oneOf"
  message: "instance failed to match exactly one schema (matched 0 out of 2)"
  schema:
    loadingURI: "http://swagger.io/v2/schema.json#"
    pointer: "/definitions/parametersList/items"
  instance:
    pointer: "/paths/~1client~1{client_id}/get/parameters/0"
```
