### ISSUE TITLE
Add "Intelligent Automation (OCR, AI,...)" API

### ISSUE THREAD

**Issue by HanneContractFit** [APIs-guru/openapi-directory#598]
**Format**: Swagger 2.0
**Official**: YES
**Url**: https://cfportal.contract-p.fit/swagger.json
**Name**: Intelligent Automation (OCR, AI,...)
**Valid**: No

**Comment by MikeRalphson** [comment]
Hi, thanks for the contribution. At your given URL I get an error message:

{"error":"Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}

**Comment by HanneContractFit** [comment]
Hi Mike,

Is this better: https://cfportal.contract-p.fit/apidoc/ 
That's our Swagger, but I thought you needed the base-URL. 

This is another url I found: https://cfportal.contract-p.fit/swagger.json

Is one of these 2 okay?

**Comment by MikeRalphson** [comment]
Thanks, it's the `swagger.json` URL we need.

Unfortunately there's some validation errors in your definition, could you look at fixing these before inclusion?

https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fcfportal.contract-p.fit%2Fswagger.json

```yaml
---
messages:
- "attribute definitions.EvaluationDataPost.definitions is unexpected"
- "attribute definitions.EvaluationDataPost.patternProperties is unexpected"
schemaValidationMessages:
- level: "error"
  domain: "validation"
  keyword: "additionalProperties"
  message: "object instance has properties which are not allowed by the schema: [\"\
    definitions\",\"patternProperties\"]"
  schema:
    loadingURI: "http://swagger.io/v2/schema.json#"
    pointer: "/definitions/schema"
  instance:
    pointer: "/definitions/EvaluationDataPost"
  required: null
  missing: null
```
