### ISSUE TITLE
Add "Credit as a Service" API

### ISSUE THREAD

**Issue by TarmoAtSmartCredit** [APIs-guru/openapi-directory#735]
**Format**: OpenAPI 3.0
**Official**: YES
**Url**: https://creditasaservice.s3.eu-central-1.amazonaws.com/SmartCreditAPI.json
**Name**: Credit as a Service

**Comment by MikeRalphson** [comment]
Thanks for the submission. The API definition fails to validate because the oAuth `scopes` are not mentioned in the `securityScheme` object.

```yaml
expected Object {
  authorizationUrl: 'https://example.com/oauth/authorize',
  tokenUrl: 'https://example.com/oauth/token'
} to have property scopes
#/components/securitySchemes/smartCredit_auth/flows/authorizationCode
```

If you amend your definition to something like:

```json
"components": {
    "securitySchemes": {
      "smartCredit_auth": {
        "type": "oauth2",
        "description": "This API uses Auth 2 with the implicit grant flow",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://example.com/oauth/authorize",
            "tokenUrl": "https://example.com/oauth/token",
            "scopes": {
              "read": "Read credit data",
              "write": "Write credit data"
            }
          }
        }
      },
```

it will validate.

Also your `externalDocs` point at `swagger.io` when they should really describe your API in human-readable terms,
