### ISSUE TITLE
APIs/adyen.com/* seems out of sync

### ISSUE THREAD

**Issue by ahl** [APIs-guru/openapi-directory#866]
Some of the yaml files checked in under APIs/adyen.com/ are invalid due to invalid tab characters. The latest version upstream seems to be fine: https://github.com/Adyen/adyen-openapi/tree/master/yaml

Is this the right upstream? The description fields in particular look different:

https://github.com/APIs-guru/openapi-directory/blob/main/APIs/adyen.com/CheckoutService/37/openapi.yaml
```yaml
        airline.leg.date_of_travel:
          description: |-
            	
            Date and time of travel. [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)-compliant.
            * Format: `yyyy-MM-dd HH:mm`
            * minLength: 16
            * maxLength: 16
          type: string
```

https://github.com/Adyen/adyen-openapi/blob/master/yaml/CheckoutService-v37.yaml
```yaml
        airline.leg.date_of_travel:
          description: "\t\nDate and time of travel. [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)-compliant.\n\
            * Format: `yyyy-MM-dd HH:mm`\n* minLength: 16\n* maxLength: 16"
          type: string
```

Note the unquoting of the "\t" causes former file to be invalid.
