### ISSUE TITLE
APIs/corona-virus-stats.herokuapp.com/v1/openapi.yaml differs from the upstream in deleterious ways

### ISSUE THREAD

**Issue by ahl** [APIs-guru/openapi-directory#867]
I noticed that `maximum` and `minimum` are set to values that cannot be represented by a signed 64-bit integer:

```yaml
          maximum: 9223372036854776000
          minimum: -9223372036854776000
          nullable: true
          title: Active cases
          type: integer
```

9223372036854776000 - 2^63 = 192

This is challenging in languages that use integers to represent integers as opposed to JavaScript that uses floating point numbers. 

The upstream json has different values:

```json
{
    "title": "Active cases",
    "type": "integer",
    "maximum": 9223372036854775807,
    "minimum": -9223372036854775808,
    "x-nullable": true
}
```

Note that these max and min correspond to the range of a signed 64-bit integer (which makes one wonder why the data even specifies maximum and minimum).

Could you modify the conversion tool to avoid making the modifications above?
